### ISSUE TITLE
error during marv fileset discard

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics#2]
Note that this is with version 2.0.0a2.

```
marv@28f5b895ed2f:/marv/site$ marv fileset discard 1efd8080-b54f-43f3-bc1e-aa389a2c0595
2016-10-10 02:39:51,408 INFO rospy.topics topicmanager initialized
libdc1394 error: Failed to initialize libdc1394
2016-10-10 02:39:51,738 INFO marv._node Registered nodes in order: ['fileset', u'md5', u'bagset_name', u'bagmeta', u'messages', u'camera_frames', u'diag_count', u'fulltext', u'gnss_plots', u'navsatfix', u'geo_json_trajectory']
Traceback (most recent call last):
  File "/marv/venv/bin/marv", line 11, in <module>
    sys.exit(cli())
  File "/marv/venv/local/lib/python2.7/site-packages/marv/cli.py", line 294, in cli
    marv(auto_envvar_prefix='MARV')
  File "/marv/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/marv/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/marv/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/marv/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/marv/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/marv/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/marv/venv/local/lib/python2.7/site-packages/marv/cli.py", line 113, in marv_fileset_discard
    app.site.remove_fileset(uuid)
  File "/marv/venv/local/lib/python2.7/site-packages/marv/_site.py", line 222, in remove_fileset
    agg = Aggregate(aggdir, load=False)
TypeError: __init__() got an unexpected keyword argument 'load'
2016-10-10 02:39:51,743 INFO rospy.core signal_shutdown [atexit]
```

**Comment by NikolausDemmel** [comment]
It does not happen with 2.0.0b1
