### ISSUE TITLE
Tagging from command line fails with a RuntimeError

### ISSUE THREAD

**Issue by Earthwings** [ternaris/marv-robotics#26]
When doing sth like
`$ marv tag --add 'some tag' some-id`
in Marv 3.1 (Release 18.02) I get
```
Traceback (most recent call last):
  File "/home/marv/marv-18-02/venv/bin/marv", line 11, in <module>
    sys.exit(cli())
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/marv_cli/__init__.py", line 131, in cli
    marv(auto_envvar_prefix='MARV')
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/marv/cli.py", line 466, in marvcli_tag
    setids = parse_setids(datasets)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/marv/cli.py", line 84, in parse_setids
    setid = db.session.query(Dataset.setid)\
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2867, in __call__
    return self.class_(**local_kw)
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 143, in __init__
    self.app = app = db.get_app()
  File "/home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 957, in get_app
    'application not registered on db instance and no application'
RuntimeError: application not registered on db instance and no applicationbound to current context
```

This seems to fix it:
```
--- /home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/marv/cli.py.org        2018-02-10 16:40:32.561860998 +0100
+++ /home/marv/marv-18-02/venv/local/lib/python2.7/site-packages/marv/cli.py    2018-02-10 16:34:06.945856438 +0100
@@ -463,8 +463,9 @@
         click.echo(ctx.get_help())
         ctx.exit(1)

+    app = create_app()
     setids = parse_setids(datasets)
-    create_app().site.tag(setids, add, remove)
+    app.site.tag(setids, add, remove)


 @marvcli.group('user')
```

**Comment by chaoflow** [comment]
@Earthwings thx! fix in upcoming 3.2 release
