### ISSUE TITLE
Login fails with internal server error if no user was created

### ISSUE THREAD

**Issue by NikolausDemmel** [ternaris/marv-robotics#8]
Minor issue: If no user has yet been created, the login fails with "internal server error". Can be easily worked around ofc by adding at least 1 user.

```
2016-10-31 21:52:11,834 ERROR marv.app Exception on /marv/api/2/login [POST]
Traceback (most recent call last):
  File "/marv/venv/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/marv/venv/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/marv/venv/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/marv/venv/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/marv/venv/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/marv/venv/local/lib/python2.7/site-packages/marv/app/webapi2.py", line 205, in login
    if current_app.site.authenticate(username, password):
  File "/marv/venv/local/lib/python2.7/site-packages/marv/_site.py", line 273, in authenticate
    with open(self.authfile) as f:
IOError: [Errno 2] No such file or directory: '/marv/site/users'
```

**Comment by chaoflow** [comment]
thx, fixed with https://github.com/ternaris/marv/commit/b250049c5e8b66f04dc5b5b025dd5d88e8ce0bd8

**Comment by NikolausDemmel** [comment]
Thanks!
